package lab.ratelimiter.gateway.application;

public enum RedisOutcome {
  NOT_APPLICABLE,
  ALLOWED,
  REJECTED,
  TIMEOUT,
  CONNECTION_FAILURE,
  SCRIPT_ERROR,
  MALFORMED_STATE,
  MALFORMED_RESPONSE,
  CLOCK_ROLLBACK,
  WINDOW_MISMATCH_EXHAUSTED
}
